// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmeuQ-Fzkk4ijidFutr3HCH7iTC68ANEk',
    appId: '1:172623457993:web:7ddccd0d5ba3fa60f5a718',
    messagingSenderId: '172623457993',
    projectId: 'stockapp-97dd4',
    authDomain: 'stockapp-97dd4.firebaseapp.com',
    storageBucket: 'stockapp-97dd4.firebasestorage.app',
    measurementId: 'G-V0LLKS5W0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcGbNKwi6ZygRvk0mdXSVxhy1648prS8',
    appId: '1:172623457993:android:eeec5e33e9091002f5a718',
    messagingSenderId: '172623457993',
    projectId: 'stockapp-97dd4',
    storageBucket: 'stockapp-97dd4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARLODa3GNnSN3z3_cTB8zjUJWvGIN-GB8',
    appId: '1:172623457993:ios:18f1ff1751b12d71f5a718',
    messagingSenderId: '172623457993',
    projectId: 'stockapp-97dd4',
    storageBucket: 'stockapp-97dd4.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARLODa3GNnSN3z3_cTB8zjUJWvGIN-GB8',
    appId: '1:172623457993:ios:18f1ff1751b12d71f5a718',
    messagingSenderId: '172623457993',
    projectId: 'stockapp-97dd4',
    storageBucket: 'stockapp-97dd4.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmeuQ-Fzkk4ijidFutr3HCH7iTC68ANEk',
    appId: '1:172623457993:web:76528da9c208f83ff5a718',
    messagingSenderId: '172623457993',
    projectId: 'stockapp-97dd4',
    authDomain: 'stockapp-97dd4.firebaseapp.com',
    storageBucket: 'stockapp-97dd4.firebasestorage.app',
    measurementId: 'G-1MQ5JVKM8H',
  );
}
